#!/bin/bash

EXTRA_ARGS=$@

rm -f CMakeCache.txt

cmake \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 \
 -D CMAKE_C_COMPILER:STRING=mpicc \
 -D CMAKE_C_FLAGS:STRING="-DWITH_MPI -DWITH_MKL -DMINIAERO" \
 \
 -D CMAKE_CXX_COMPILER:STRING=mpic++ \
 -D CMAKE_CXX_FLAGS:STRING="-DWITH_MPI -DWITH_MKL -DMINIAERO" \
 \
 -D CXX_INCLUDE_DIRS:PATH="/sierra/Sntools/extras/compilers/intel/Compiler/11.1/064/include" \
 \
 -D CMAKE_INSTALL_PREFIX:PATH=".." \
 \
 -D SPARC_BUILD_LABEL="icc-mkl-openmpi-opt" \
 \
 -D TPL_ENABLE_MPI:BOOL=ON \
 -D MPI_INCLUDE_DIRS:PATH="/sierra/Sntools/extras/mpi/RHEL5/openmpi-1.4.2/intel-11.1.064-64Bit/include" \
 -D MPI_LIBRARY_DIRS:PATH="/sierra/Sntools/extras/mpi/RHEL5/openmpi-1.4.2/intel-11.1.064-64Bit/lib" \
 -D MPI_LIBRARIES:STRING="mpi" \
 \
 -D TPL_ENABLE_CBLAS:BOOL=ON \
 -D CBLAS_INCLUDE_DIRS:PATH="/sierra/Sntools/extras/compilers/intel/Compiler/11.1/064/mkl/include" \
 -D CBLAS_LIBRARY_DIRS:PATH="/sierra/Sntools/extras/compilers/intel/Compiler/11.1/064/mkl/lib/em64t;/sierra/Sntools/extras/compilers/intel/Compiler/11.1/064/lib/intel64" \
 -D CBLAS_LIBRARIES:STRING="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5;pthread" \
 \
 $EXTRA_ARGS ..
