#!/bin/bash

EXTRA_ARGS=$@

rm -rf CMakeFiles
rm -f CMakeCache.txt

cmake \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 \
 -D CMAKE_C_COMPILER:STRING=gcc \
 -D CMAKE_C_FLAGS:STRING="-DWITH_MPI"\
 \
 -D CMAKE_CXX_COMPILER:STRING=g++ \
 -D CMAKE_CXX_FLAGS:STRING="-DWITH_MPI"\
 \
 -D MPI_INCLUDE_DIRS:PATH="/opt/cray/mpt/6.1.1/gni/mpich2-gnu/48/include" \
 -D MPI_LIBRARY_DIRS:PATH="/opt/cray/mpt/6.1.1/gni/mpich2-gnu/48/lib" \
 \
 -D CMAKE_EXE_LINKER_FLAGS:STRING="-lpthread -lmpich -L/home/kjfrank/hwloc/lib -lhwloc" \
 \
 -D CMAKE_INSTALL_PREFIX:PATH=".." \
 \
 -D Kokkos_ENABLE_Cuda:BOOL=OFF \
 -D TPL_ENABLE_HWLOC:BOOL=ON \
 -D TPL_ENABLE_Pthread:BOOL=ON \
 -D HWLOC_LIB_DIRS:FILEPATH="/home/kjfrank/hwloc/lib" \
 -D HWLOC_INCLUDE_DIRS:FILEPATH="/home/kjfrank/hwloc/include" \
 $EXTRA_ARGS ..

CONFIG="../kokkos/core/src/KokkosCore_config.h"

rm -f ${CONFIG}

echo "#ifndef KOKKOS_CORE_CONFIG_H" >> ${CONFIG}
echo "#define KOKKOS_CORE_CONFIG_H" >> ${CONFIG}
echo "#define KOKKOS_HAVE_PTHREAD" >> ${CONFIG}
echo "#define KOKKOS_HAVE_HWLOC" >> ${CONFIG}
echo "#endif" >> ${CONFIG}
